name: Frontend-CI

on:
  push:
    branches:
      - main
      - "feature/**" # This will trigger the workflow for all branches that start with feature/-
    # paths:
    #   - frontend/** # This will trigger the workflow for all changes in the frontend directory
  pull_request:
    branches:
      - main
      - "feature/**" # This will trigger the workflow for all branches that start with feature/-
    # paths:
    #   - frontend/** # This will trigger the workflow for all changes in the frontend directory

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run Unit Tests with Vitest
      - name: Run Unit Tests
        run: |
          npm run test

      # Build the frontend
      - name: Build frontend
        run: |
          npm run build
